# Generated by Django 5.2.1 on 2025-05-19 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tmdb_id', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TMDBTVSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(default=None, max_length=9999, null=True)),
                ('tmdb_id', models.PositiveBigIntegerField(unique=True)),
                ('img_fetch_path', models.CharField(max_length=50)),
                ('img_path', models.CharField(max_length=50, null=True)),
                ('cast', models.JSONField()),
                ('crew', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('season_number', models.PositiveIntegerField()),
                ('air_date', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TMDBMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(default=None, max_length=9999, null=True)),
                ('tmdb_id', models.PositiveBigIntegerField(unique=True)),
                ('img_fetch_path', models.CharField(max_length=50)),
                ('img_path', models.CharField(max_length=50, null=True)),
                ('cast', models.JSONField()),
                ('crew', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('release_date', models.CharField(max_length=10)),
                ('runtime', models.PositiveIntegerField()),
                ('genres', models.ManyToManyField(to='tmdb.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TMDBTVEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(default=None, max_length=9999, null=True)),
                ('tmdb_id', models.PositiveBigIntegerField(unique=True)),
                ('img_fetch_path', models.CharField(max_length=50)),
                ('img_path', models.CharField(max_length=50, null=True)),
                ('cast', models.JSONField()),
                ('crew', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('air_date', models.CharField(max_length=10)),
                ('runtime', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tmdb.tmdbtvseason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TMDBTVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(default=None, max_length=9999, null=True)),
                ('tmdb_id', models.PositiveBigIntegerField(unique=True)),
                ('img_fetch_path', models.CharField(max_length=50)),
                ('img_path', models.CharField(max_length=50, null=True)),
                ('cast', models.JSONField()),
                ('crew', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_seasons', models.PositiveIntegerField()),
                ('total_episodes', models.PositiveIntegerField()),
                ('first_air_date', models.CharField(max_length=10)),
                ('last_air_date', models.CharField(max_length=10)),
                ('genres', models.ManyToManyField(to='tmdb.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tmdbtvseason',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tmdb.tmdbtvseries'),
        ),
    ]
