# Generated by Django 5.2.1 on 2025-05-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='cast',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='crew',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tmdbtvepisode',
            name='cast',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tmdbtvepisode',
            name='crew',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tmdbtvseason',
            name='cast',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tmdbtvseason',
            name='crew',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tmdbtvseries',
            name='cast',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tmdbtvseries',
            name='crew',
            field=models.JSONField(null=True),
        ),
    ]
