# Generated by Django 5.2.1 on 2025-05-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_alter_tmdbmovie_cast_alter_tmdbmovie_crew_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmdbmovie',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='tmdbtvepisode',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='tmdbtvseason',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='tmdbtvseries',
            name='img_path',
        ),
    ]
