# Generated by Django 5.2.1 on 2025-05-23 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0004_rename_img_fetch_path_tmdbmovie_img_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbtvepisode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tmdb.tmdbtvseason'),
        ),
        migrations.AlterField(
            model_name='tmdbtvseason',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tmdb.tmdbtvseries'),
        ),
    ]
