# Generated by Django 5.2.1 on 2025-05-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflix', '0002_remove_account_email_remove_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(null=True, to='djangoflix.watchablecontent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=16),
        ),
    ]
