# Generated by Django 5.2.1 on 2025-05-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflix', '0003_alter_profile_favorites_alter_profile_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='djangoflix.watchablecontent'),
        ),
    ]
