# Generated by Django 5.2.1 on 2025-05-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflix', '0004_alter_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.CharField(default='default.png', max_length=30),
        ),
    ]
