# Generated by Django 5.2.1 on 2025-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflix', '0005_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(choices=[('default.png', 'default.png'), ('boy_blue.png', 'boy_blue.png'), ('girl_blue.png', 'girl_blue.png'), ('boy_brown.png', 'boy_brown.png'), ('girl_brown.png', 'girl_brown.png'), ('boy_red.png', 'boy_red.png'), ('girl_red.png', 'girl_red.png'), ('girl_blond.png', 'girl_blond.png'), ('girl_green.png', 'girl_green.png'), ('girl_pink.png', 'girl_pink.png'), ('clown.png', 'clown.png'), ('king.png', 'king.png'), ('princess.png', 'princess.png'), ('mermaidA.png', 'mermaidA.png'), ('mermaidB.png', 'mermaidB.png')], default='default.png', max_length=30),
        ),
    ]
