# Generated by Django 5.2.1 on 2025-05-23 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflix', '0006_alter_profile_icon'),
        ('tmdb', '0004_rename_img_fetch_path_tmdbmovie_img_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchablecontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='watchablecontent',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='watchablecontent',
            name='title',
        ),
        migrations.AddField(
            model_name='watchablecontent',
            name='cast',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='watchablecontent',
            name='crew',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='watchablecontent',
            name='genres',
            field=models.ManyToManyField(to='tmdb.genre'),
        ),
        migrations.AddField(
            model_name='watchablecontent',
            name='img_path',
            field=models.CharField(default='/missing.png', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchablecontent',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchablecontent',
            name='overview',
            field=models.CharField(default=None, max_length=9999, null=True),
        ),
        migrations.CreateModel(
            name='TVSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(default=None, max_length=9999, null=True)),
                ('img_path', models.CharField(max_length=50)),
                ('cast', models.JSONField(null=True)),
                ('crew', models.JSONField(null=True)),
                ('season_number', models.PositiveIntegerField()),
                ('air_date', models.CharField(max_length=10)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='djangoflix.watchablecontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TVEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(default=None, max_length=9999, null=True)),
                ('img_path', models.CharField(max_length=50)),
                ('cast', models.JSONField(null=True)),
                ('crew', models.JSONField(null=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('air_date', models.CharField(max_length=10)),
                ('runtime', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='djangoflix.tvseason')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
