# Generated by Django 5.2.1 on 2025-05-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflix', '0008_alter_tvseason_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisode',
            name='tmdb_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvseason',
            name='tmdb_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='watchablecontent',
            name='tmdb_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
